# Generated by Django 5.1.4 on 2025-01-23 20:16

from django.db import migrations


def populate_course_relations(apps, schema_editor):
    Department = apps.get_model('schedule', 'Department')
    Course = apps.get_model('schedule', 'Course')
    Semester = apps.get_model('schedule', 'Semester')
    
    # Create a default department if none exists
    default_dept, _ = Department.objects.get_or_create(
        code='DEFAULT',
        defaults={'name': 'Default Department'}
    )
    
    # Create default semester if none exists
    default_semester, _ = Semester.objects.get_or_create(
        code='S1',
        department=default_dept
    )
    
    # Update all courses that have null department or semester
    Course.objects.filter(department__isnull=True).update(department=default_dept)
    Course.objects.filter(semester__isnull=True).update(semester=default_semester)

def reverse_populate_course_relations(apps, schema_editor):
    pass  # We don't want to reverse this migration

class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            populate_course_relations,
            reverse_populate_course_relations
        ),
    ]
