# Generated by Django 5.1.4 on 2025-01-23 20:18

from django.db import migrations, models
import django.db.models.deletion

def get_default_department():
    from schedule.models import Department
    dept, _ = Department.objects.get_or_create(
        code='DEFAULT',
        defaults={'name': 'Default Department'}
    )
    return dept.code

def get_default_semester():
    from schedule.models import Department, Semester
    dept, _ = Department.objects.get_or_create(
        code='DEFAULT',
        defaults={'name': 'Default Department'}
    )
    semester, _ = Semester.objects.get_or_create(
        code='S1',
        department=dept
    )
    return semester.id

class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_populate_course_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='courses',
                to='schedule.department',
                default=get_default_department
            ),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='courses',
                to='schedule.semester',
                default=get_default_semester
            ),
        ),
    ]
